using HRSystem.API.Data;
using HRSystem.API.DTOs;
using HRSystem.API.Models;
using Microsoft.EntityFrameworkCore;

namespace HRSystem.API.Services
{
    public class EmployeeService : IEmployeeService
    {
        private readonly AppDbContext _context;

        public EmployeeService(AppDbContext context)
        {
            _context = context;
        }

        public async Task<List<EmployeeDto>> GetAllAsync()
        {
            return await _context.Employees
                .Select(e => new EmployeeDto
                {
                   EmployeeId = e.EmployeeId,
                    CompanyId = e.CompanyId,
                    EmployeeCode = e.EmployeeCode,
                    FirstName = e.FirstName,
                    LastName = e.LastName,
                    Email = e.Email,
                    PassportNumber = e.PassportNumber,
                    DateOfBirth = e.DateOfBirth
                })
                .ToListAsync();
        }

        public async Task<EmployeeDto> GetByIdAsync(int id)
        {
            var e = await _context.Employees.FindAsync(id);
            if (e == null) return null;

            return new EmployeeDto
            {
                EmployeeId = e.EmployeeId,
                CompanyId = e.CompanyId,
                EmployeeCode = e.EmployeeCode,
                FirstName = e.FirstName,
                LastName = e.LastName,
                Email = e.Email,
                PassportNumber = e.PassportNumber,
                DateOfBirth = e.DateOfBirth
            };
        }

        public async Task<EmployeeDto> CreateAsync(EmployeeDto dto)
        {
            var departmentExists = await _context.Department.AnyAsync(d => d.DepartmentId == dto.DepartmentId);
            if (!departmentExists)
                throw new Exception("Invalid DepartmentId.");
            var entity = new Employee
            {
                //EmployeeId = dto.EmployeeId, // Optional if auto-generated by DB
                CompanyId = dto.CompanyId,
                DepartmentId = dto.DepartmentId, // ✅ Ensure this property exists in your DTO

                EmployeeCode = dto.EmployeeCode,
                FirstName = dto.FirstName,
                LastName = dto.LastName,
                DateOfBirth = dto.DateOfBirth,
                Gender = dto.Gender,
                Nationality = dto.Nationality,
                MotherName = dto.MotherName,
                HomeCountryAddress = dto.HomeCountryAddress,
                HomeCountryPhone = dto.HomeCountryPhone,
                EmergencyContactName = dto.EmergencyContactName,
                EmergencyPhone = dto.EmergencyPhone,
                Email = dto.Email,
                PassportNumber = dto.PassportNumber,
                PassportExpiry = dto.PassportExpiry,
                PassportCountry = dto.PassportCountry,
                PhotoPath = dto.PhotoPath,

            };

            _context.Employees.Add(entity);
            await _context.SaveChangesAsync();

            dto.EmployeeId = entity.EmployeeId;
            return dto;
        }

      public async Task<EmployeeDto> UpdateAsync(int id, EmployeeDto dto)
{
    var e = await _context.Employees.FindAsync(id);
    if (e == null) return null;

    e.CompanyId = dto.CompanyId;
    e.EmployeeCode = dto.EmployeeCode;
    e.FirstName = dto.FirstName;
    e.LastName = dto.LastName;
    e.DateOfBirth = dto.DateOfBirth;
    e.Gender = dto.Gender;
    e.Nationality = dto.Nationality;
    e.MotherName = dto.MotherName;
    e.HomeCountryAddress = dto.HomeCountryAddress;
    e.HomeCountryPhone = dto.HomeCountryPhone;
    e.EmergencyContactName = dto.EmergencyContactName;
    e.EmergencyPhone = dto.EmergencyPhone;
    e.Email = dto.Email;
    e.PassportNumber = dto.PassportNumber;
    e.PassportExpiry = dto.PassportExpiry;
    e.PassportCountry = dto.PassportCountry;
    e.PhotoPath = dto.PhotoPath;

    await _context.SaveChangesAsync();
    return dto;
}


        public async Task<bool> DeleteAsync(int id)
        {
            var e = await _context.Employees.FindAsync(id);
            if (e == null) return false;

            _context.Employees.Remove(e);
            await _context.SaveChangesAsync();
            return true;
        }
    }
}
